### ISSUE TITLE
Reference links

### ISSUE THREAD

**Issue by bfontaine** [sagotch/pastek-lang#1]
Do you plan to support reference links, like Markdown? See example below:

```
Here is a [link][a-ref] and [another][] with an implicit reference.

[a-ref]: http://example.com/foo
[another]: http://example.com/bar
```

This is handy when you have long links, for exemple here is an excerpt of a [Wikipedia article](https://en.wikipedia.org/wiki/Rambles_in_Germany_and_Italy) with expanded links:

```
**Rambles in Germany and Italy**, in 1840, 1842, and 1843 is a [travel
narrative](https://en.wikipedia.org/wiki/Travel_literature) by the British
[Romantic](https://en.wikipedia.org/wiki/Romanticism) author [Mary
Shelley](https://en.wikipedia.org/wiki/Mary_Shelley). Issued in 1844, it is her
last published work. Published in two volumes, the text describes two European
trips that Mary Shelley took with her son, [Percy Florence
Shelley](https://en.wikipedia.org/wiki/Percy_Florence_Shelley), and several of
his university friends. Mary Shelley had lived in Italy with her husband,
[Percy Bysshe Shelley](https://en.wikipedia.org/wiki/Percy_Bysshe_Shelley),
between 1818 and 1823.
```

And here is the same excerpt using references:

```
**Rambles in Germany and Italy**, in 1840, 1842, and 1843 is a [travel
narrative][1] by the British [Romantic][2] author [Mary Shelley][3]. Issued in
1844, it is her last published work. Published in two volumes, the text
describes two European trips that Mary Shelley took with her son, [Percy
Florence Shelley][4], and several of his university friends. Mary Shelley had
lived in Italy with her husband, [Percy Bysshe Shelley][5], between 1818 and
1823.

[1]: https://en.wikipedia.org/wiki/Travel_literature
[2]: https://en.wikipedia.org/wiki/Romanticism
[3]: https://en.wikipedia.org/wiki/Mary_Shelley
[4]: https://en.wikipedia.org/wiki/Percy_Florence_Shelley
[5]: https://en.wikipedia.org/wiki/Percy_Bysshe_Shelley
```

**Comment by sagotch** [comment]
It seems to be a must-have, so yes.

But I want to keep the same idea than `[[ url << text ]]` format. I'll think about it (or perhaps you have something to propose).

**Comment by sagotch** [comment]
```
Here is a [[ a-ref << some very **interesting** text ]]
and [[another]] with an implicit reference.

[[ a-ref ]]: http://example.com/foo
[[ another ]]: http://example.com/bar
```

The idea is to treat each url as an alias. When rendering, if no value for this alias is found in the document, use it as url.

But I have to keep thinking about where to store these definitions during parsing. As rendering engines have no knowledge about the actual document but only about its configuration, I might use a global `links : Toml.tomlTable` to store them and merge them in the configuration table.

Notes:
- multiple definitions will not be accepted (in order to prevent unexpected redirection).
- only url-friendly (according to pastek) characters could be used in references.

**Comment by sagotch** [comment]
Version 2014.03.08 uses `[[ a-ref ]] :: [[ http://example.com/foo ]]`.

**Comment by sagotch** [comment]
Todo: Allow url rewriting for images too.

**Comment by sagotch** [comment]
Seems broken when multiple re-definitions follow.
