### ISSUE TITLE
UML support (with plantuml ?)

### ISSUE THREAD

**Issue by nikayou** [sagotch/pastek-lang#18]
Wouldn't it be nice to be able to define UML diagrams inside pastek files ? The same way it supports Graphviz, it could support an UML modeler, for instance PlantUML.

**Comment by sagotch** [comment]
It actually does.

Add something like this somewhere in your file

```
%{
    [cmd]
        plantuml = "plantuml -tsvg"
%}
```

And then:

```
%%%plantuml
@startuml

Class01 "1" *-- "many" Class02 : contains

Class03 o-- Class04 : agregation

Class05 --> "1" Class06

@enduml
%%%
```
