### ISSUE TITLE
Error while installing pastek.0.5.0 with opam on mac OSX 10.9.5

### ISSUE THREAD

**Issue by Gnukos** [sagotch/pastek-lang#21]
=-=-= Installing pastek.0.5.0 =-=-=
pastek.0.5.0 Fetching https://github.com/pastek-project/pastek.git#v0.5.0
Copying ~/.opam/repo/pastek/packages/pastek/pastek.0.5.0/files/pastek.install to ~/.opam/4.01.0/build/pastek.0.5.0/
Building pastek.0.5.0:
  make build
[ERROR] The compilation of pastek.0.5.0 failed.
Removing pastek.0.5.0.
  ocamlfind remove pastek

===== ERROR while installing pastek.0.5.0 =====
# opam-version 1.1.2
# os           darwin
# command      make build
# path         /Users/gnukos/.opam/4.01.0/build/pastek.0.5.0
# compiler     4.01.0
# exit-code    2
# env-file     /Users/gnukos/.opam/4.01.0/build/pastek.0.5.0/pastek-33078-d0f245.env
# stdout-file  /Users/gnukos/.opam/4.01.0/build/pastek.0.5.0/pastek-33078-d0f245.out
# stderr-file  /Users/gnukos/.opam/4.01.0/build/pastek.0.5.0/pastek-33078-d0f245.err
### stdout ###
# make -C src/ build
# ocamlfind ocamlc  -package unix,str,toml -c type.ml
# menhir parser.mly
# ocamlfind ocamlc  -package unix,str,toml -c parser.mli
### stderr ###
# File "parser.mli", line 42, characters 60-70:
# Error: Unbound type constructor Toml.table
# make[1]: **\* [parser.cmi] Error 2
# make: **\* [build] Error 2

The former state can be restored with opam switch import -f "/Users/gnukos/.opam/4.01.0/backup/state-20140910162505.export"
'opam install pastek' failed.

**Comment by sagotch** [comment]
Ah... That should be because pastek needs TOML v2.0, which is not released on main opam repo yet.

```
opam repository add sagotch https://github.com/sagotch/opam-repo-dev.git
opam update
opam install toml / opam upgrade
opam install pastek
```

**Comment by Gnukos** [comment]
Thx ;)
